export PATH := $(GOPATH)/bin:$(PATH)
export OLDGOPATH := $(GOPATH)
export GOPATH := $(shell pwd)/Godeps/_workspace:$(GOPATH)

all: build

build: gox app 

gox:
	GOPATH=$(OLDGOPATH) go get github.com/mitchellh/gox

app:
	gox -osarch "darwin/386 darwin/amd64 linux/386 linux/amd64 linux/arm windows/386 windows/amd64" ./src/...
