#!/bin/sh /etc/rc.common



START=50
STOP=50
USE_PROCD=1

NAME=frps
PROG=/usr/bin/"${NAME}"
CONFIGFILE=/etc/frp/"${NAME}".ini

start_service(){
    procd_open_instance "${NAME}"
    procd_set_param command "${PROG}" -c "${CONFIGFILE}"
    procd_set_param file "${CONFIGFILE}"
    procd_set_param respawn
    
    procd_set_param user nobody #root can use 1~1024 ports
    
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

reload_service(){
    restart
}
