#!/bin/sh /etc/rc.common



START=50
STOP=50

USE_PROCD=1
PROG=/usr/bin/frps
CONFFILE=/etc/frp/frps.ini

start_service(){
    procd_open_instance
    procd_set_param command "${PROG}" -c "${CONFFILE}"
    procd_set_param file "${CONFFILE}"
    procd_set_param user nobody
    procd_set_param respawn
    
    procd_set_param watch network.interface
    procd_set_param netdev dev
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

reload_service(){
    restart
}
