bindPort = 7000

# Controls which IPs can connect to this FRP server to create tunnels
# For per-proxy IP restrictions, use allowedAccessIPs in client config (frpc.toml)
# allowedAccessIPs = ["127.0.0.1", "192.168.1.0/24"]
