FROM golang:1.18-alpine3.15 AS building

COPY . /building
WORKDIR /building

RUN apk --no-cache add \
    git \
 && export GO111MODULE=on \
 && env CGO_ENABLED=0 go build -trimpath -ldflags "-s -w" -o ./bin/frpc ./cmd/frpc

FROM alpine:3.15
LABEL maintainer="i@muir.fun"

COPY --from=building /building/bin/frpc /usr/bin/frpc

ENTRYPOINT ["/usr/bin/frpc"]
CMD ["-h"]