FROM golang:1.23 AS building
COPY . /building
WORKDIR /building
RUN make frps && make frpc

FROM alpine:3
WORKDIR /frp
RUN apk add --no-cache tzdata
COPY --from=building /building/bin/frps /frp/frps
COPY --from=building /building/bin/frpc /frp/frpc
ENV mode=frps
CMD ["/bin/sh", "-c", "./$mode -c $mode.toml"]
