/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    LongSpan: typeof import('./src/components/LongSpan.vue')['default']
    ProxiesHTTP: typeof import('./src/components/ProxiesHTTP.vue')['default']
    ProxiesHTTPS: typeof import('./src/components/ProxiesHTTPS.vue')['default']
    ProxiesSTCP: typeof import('./src/components/ProxiesSTCP.vue')['default']
    ProxiesSUDP: typeof import('./src/components/ProxiesSUDP.vue')['default']
    ProxiesTCP: typeof import('./src/components/ProxiesTCP.vue')['default']
    ProxiesUDP: typeof import('./src/components/ProxiesUDP.vue')['default']
    ProxyView: typeof import('./src/components/ProxyView.vue')['default']
    ProxyViewExpand: typeof import('./src/components/ProxyViewExpand.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerOverview: typeof import('./src/components/ServerOverview.vue')['default']
    Traffic: typeof import('./src/components/Traffic.vue')['default']
  }
}
