FROM golang AS builder
WORKDIR /frp
COPY go.mod .
COPY go.sum .
COPY Makefile .
RUN make fmt
COPY . .
RUN make frpc-arm64

FROM arm64v8/golang:alpine
WORKDIR /
COPY --from=builder /frp/bin/arm64/frpc /usr/local/bin/frpc
COPY --from=builder /frp/conf/frpc.ini /etc/frpc.ini
CMD ["frpc", "--config", "/etc/frpc.ini"]
