name: Security Scan

on:
  schedule:
  - cron: "0 13 * * 1"
  push:
    branches:
    - master
    - dev
  pull_request:
    branches:
    - master
    - dev

jobs:
  vulncheck:
    name: Scan for vulnerabilities in Go code
    runs-on: ubuntu-latest
    steps:
    - name: govulncheck
      uses: golang/govulncheck-action@v1
